spring:
  application:
    name: DiscoveryService

---

spring:
  config:
    activate:
      on-profile: dev
    import: optional:ConfigService:http://localhost:8888
  cloud:
    config:
      fail-fast: true